namespace MusicStore.Models
{// IMPORTANT: Represents a generated song with metadata.
    public class Song
    {
        public int Index { get; set; }
        public string Title { get; set; } = "";
        public string Artist { get; set; } = "";
        public string Album { get; set; } = "";
        public string Genre { get; set; } = "";
        public int Likes { get; set; }
        public List<string> Notes { get; set; } = new();// IMPORTANT: Deterministic note sequence used for audio generation.
        public int Duration { get; set; }
        public string Review { get; set; } = "";
        // IMPORTANT: Lazy-loaded cover URL generated by ImageService
        public string? CoverImageUrl { get; set; }
    }
}
